on:
  pull_request:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dprint/check@v2.3
    - run: dprint config update
  isort:
    # https://stackoverflow.com/a/78156861
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
      with:
        args: check --select I --fix .
    - run: ruff format .
    - run: git diff-index --patch --color --exit-code HEAD
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip3 install mypy
    - run: mypy .
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
