on:
  pull_request:
  push:
jobs:
  dprint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dprint/check@v2.3
    - run: dprint config update

  ruff-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
      with:
        version: 0.13.2

  # https://stackoverflow.com/a/78156861
  ruff-isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
      with:
        version: 0.13.2
        args: check --select I --fix
    - run: git diff-index --patch --color --exit-code HEAD

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip3 install 'mypy>=1.18.0'
    - run: mypy .
