on:
  push: {}
  pull_request:
    branches:
    - master
    - ci

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v17
    - run: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - run: nix-channel --update
    - uses: actions/checkout@v4
    - run: nix-build --show-trace -E '(import <nixpkgs> {}).python3.pkgs.callPackage ./. {}'
