on:
  push: {}
  pull_request:
    branches:
    - master
    - ci

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://nixos/nix:latest
      with:
        args: nix-channel --update
